import './globals.scss';
import type { Metadata, Viewport } from 'next';
import { Noto_Sans_KR } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Knock',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

const notoSansKR = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-noto-sans-kr',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={notoSansKR.variable}>
        <div>{children}</div>
      </body>
    </html>
  );
}
